russian-doll-caching/config/routes.rb
RussianDollCaching::Application.routes.draw do
  resources :pre_posts
  resources :russian_doll_posts

end

russian-doll-caching/app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :name, :content, :user

  belongs_to :post, touch: true
  belongs_to :user
end

russian-doll-caching/app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :title, :content, :user

  belongs_to :user
  has_many :comments
end

russian-doll-caching/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name
end

russian-doll-caching/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end
end

russian-doll-caching/app/controllers/pre_posts_controller.rb
class PrePostsController < ApplicationController
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  def show
    @post = Post.includes(comments: :user).find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end
end

russian-doll-caching/app/controllers/russian_doll_posts_controller.rb
class RussianDollPostsController < ApplicationController
  def show
    @post = Post.find(params[:id])
    @presenter = PostPresenter.new(@post)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  #def index
  #    @posts = Post.all
  #
  #    respond_to do |format|
  #      format.html # index.html.erb
  #      format.json { render json: @posts }
  #    end
  #  end
end

russian-doll-caching/app/helpers/posts_helper.rb
module PostsHelper
end

russian-doll-caching/app/helpers/russian_doll_posts_helper.rb
module RussianDollPostsHelper
end

russian-doll-caching/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Russian Doll Caching Blog Demo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

russian-doll-caching/app/views/posts/show.html.erb
<div class="post">
  <%= render @post %>

  <hr/>

  <div class="comments">
    <% @post.comments.each do |comment| %>
      <div id="comment-<%=comment.id%>">
        <%= comment.name %> says:
        <p>
          <%= comment.content %>
        </p>
      </div>
    <% end %>
   </div>
</div>

russian-doll-caching/app/views/pre_posts/_post.html.erb
<div id="post-<%=post.id%>">
  <h1><%= link_to post.title, pre_post_path(post) %></h1>
  <h3><%= post.user.name %></h3>
  <div class="content">
    <%= post.content %>
  </div>
</div>

russian-doll-caching/app/views/pre_posts/index.html.erb
<h1>Russian Doll Caching Blog Demo</h1>
<br/>
<% @posts.each do |post| %>
  <%= render partial: 'post', locals: {post: post} %>
<% end %>

russian-doll-caching/app/views/pre_posts/show.html.erb
<div class="post">
  <%= render partial: 'post', locals: {post: @post} %>

  <hr/>

  <div class="comments">
    <% @post.comments.each do |comment| %>
      <div id="comment-<%=comment.id%>">
        <%= comment.user.name %> says:
        <p>
          <%= comment.content %>
        </p>
      </div>
    <% end %>
   </div>
</div>

russian-doll-caching/app/views/russian_doll_posts/_post.html.erb
<div id="post-<%=post.id%>">
  <h1><%= link_to post.title, russian_doll_post_path(post) %></h1>
  <h3><%= post.user.name %></h3>
  <div class="content">
    <%= post.content %>
  </div>
</div>

russian-doll-caching/app/views/russian_doll_posts/index.html.erb
<h1>Russian Doll Caching Blog Demo</h1>
<br/>
<% @posts.each do |post| %>
  <%= render partial: 'post', locals: {post: post} %>
<% end %>

russian-doll-caching/app/views/russian_doll_posts/show.html.erb
<% cache @post do %>
  <div class="post">
    <%= render partial: 'post', locals: {post: @post} %>

    <hr/>

    <div class="comments">
      <% @presenter.comments.each do |comment| %>
        <% cache comment do %>
          <div id="comment-<%=comment.id%>">
            <%= comment.user.name %> says:
            <p>
              <%= comment.content %>
            </p>
          </div>
        <% end %>
      <% end %>
     </div>
  </div>
<% end %>